#!/usr/bin/env bash
# configures a new server
sudo apt-get update
sudo apt-get -y install nginx
service nginx start
sed -i '/sendfile on;/a \\tadd_header X-Served-By '$HOSTNAME';' /etc/nginx/nginx.conf
service nginx restart
