#!/usr/bin/env bash
# install HAproxy and confugure it
sudo apt-get -y update
sudo apt-get install -y haproxy=1.5\*
FILE=/etc/haproxy/haproxy.cfg
echo "listen 355-lb-01" | sudo tee -a $FILE
echo "bind *:80" | sudo tee -a $FILE
echo "mode http" | sudo tee -a $FILE
echo "balance roundrobin" | sudo tee -a $FILE
echo "server 2062-web-02 35.196.67.203 check" | sudo tee -a $FILE
echo "server 2062-web-01 34.75.13.177 check" | sudo tee -a $FILE
sudo service haproxy restart
