#!/usr/bin/env bash
# install HAproxy and confugure it
udo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy

echo "
frontend Local_Server
bind *:80
mode http
default_backend My_Web_Servers
backend My_Web_Servers
mode http
balance roundrobin
server 2062-web-01 34.75.13.177 check
server 2062-web-02 35.196.67.203 check
sudo " >> /etc/haproxy/haproxy.cfg
sudo service haproxy res
