#!/usr/bin/env bash
# install HAproxy and confugure it
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy
echo "listen 2062-lb-01" | sudo tee -a $FILE
echo "bind *:80" | sudo tee -a $FILE
echo "mode http" | sudo tee -a $FILE
echo "balance roundrobin" | sudo tee -a $FILE
echo "server 2062-web-02 35.196.67.203 check" | sudo tee -a $FILE
echo "server 2062-web-01 34.75.13.177 check" | sudo tee -a $FILE
sudo service haproxy restart
