#!/usr/bin/env bash
# PID And Proccess
file=/var/run/holbertonscript.pid
trap 'echo I hate the kill command; rm $file; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm $file; exit' SIGQUIT
echo $$ > $file
while true; do
	echo "To infinity and beyond"
	sleep 2
done
