#!/usr/bin/env bash
# This script iss displaying "Holberton School" 10 times
x="0"
while [ $x -lt 10 ]
do
if [ $x == 3 ] 
then
echo "bad luck"
elif [ $x == 7 ] 
then
echo "good luck"
else
echo "Holberton School"
fi
x=$((x + 1))
done
